import Head from 'next/head'
import ProductCard from 'components/productCard'
import IntroCard from 'components/introCard'
import styles from "../styles/Home.module.scss"
import HorizontalScroller from 'components/horizontalScroller'
import { useSession, signIn, signOut } from 'next-auth/react'
import ShimmerCard from 'components/shimmerCard/ShimmerCard'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={()=>signIn('google')}>signin</button>
        <button onClick={()=>signOut()}>sign out</button>
        <div className={styles.container}>
          {/* <ShimmerCard/> */}
          <IntroCard />
          <HorizontalScroller>
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
          </HorizontalScroller>
          <HorizontalScroller>
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
          </HorizontalScroller>
          <HorizontalScroller>
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
          </HorizontalScroller>
        </div>
      </main>
    </>
  )
}
